spring.application.name=GymCRM
spring.datasource.url=${URL-DB}
spring.datasource.username=${USER}
spring.datasource.password=${PASSWORD}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
